### PR TITLE
fix logger usage error

### PR DESCRIPTION
**Pull request by brainelectronics**
### Fixed
- Logger import fixed, see #31
- Examples README improved with MicroPython port specific UART pin usage example, see #30

### CODE REVIEW

**Comment by brainelectronics** [comment]
@waza-ari may you can verify the fix [0.15.1](https://github.com/brainelectronics/micropython-nextion/releases/tag/0.15.1-rc8.dev33) with

```python
import mip
import network

station = network.WLAN(network.STA_IF)
station.active(True)
station.connect('SSID', 'PASSWORD')
station.isconnected()

mip.install("github:brainelectronics/micropython-nextion", version="bugfix/fix-logger-import-issue")
```

**Comment by waza-ari** [comment]
Hi @brainelectronics, happy to test it! I'm currently out, will let you know within the next hour or so. Thanks for the quick fix!

**Comment by waza-ari** [comment]
There's one more issue I forgot to mention previously - they've also renamed the logging module.

It's now no longer called `ulogging`, it's called `logging`. It's the same codebase though. I solved it by placing a file `ulogging.py` into the `/lib` folder which contains nothing but `from logging import *`. There's got to be a more elegant way though.

That being said, the installation fails, as you've added `nextion_crop.py` to `package.json` which doesn't exist in the repo:

https://github.com/brainelectronics/micropython-nextion/blob/2face4155d31001a9bf41bc5211049ce9e2e145e/package.json#L23-L26

Full message for reference:

```
>>> mip.install("github:brainelectronics/micropython-nextion", version="bugfix/fix-logger-import-issue")
Installing github:brainelectronics/micropython-nextion/package.json to /lib
Copying: /lib/nextion/__init__.py
Copying: /lib/nextion/common.py
Copying: /lib/nextion/const.py
Copying: /lib/nextion/nextion_button.py
Copying: /lib/nextion/nextion_checkbox.py
Error 404 requesting https://raw.githubusercontent.com/brainelectronics/micropython-nextion/bugfix/fix-logger-import-issue/nextion/nextion_crop.py
File not found: nextion/nextion_crop.py github:brainelectronics/micropython-nextion/nextion/nextion_crop.py
Package may be partially installed
```

**Review by brainelectronics — COMMENTED** [review]
LGTMyself, may you can double check @waza-ari ?

```python
import mip
mip.install("github:brainelectronics/micropython-nextion", version="bugfix/fix-logger-import-issue")
```

**Comment by waza-ari** [comment]
@brainelectronics tested on RP2 Pico, installation and everything I used so far works like a charm. Thanks so much for your work!

**Pull request merged**
